config/routes.rb
RedmineApp::Application.routes.draw do
  namespace :admin do
    resources :mail_ticket_providers
    resources :mail_job_schedules
  end

  match '/admin/mail_job_schedules/start_mail_sync/:id', to: 'admin/mail_job_schedules#start_mail_sync', as: 'start_mail_sync', via: [:get]
  match '/auth/:provider/oauth', to: 'admin/mail_job_schedules#login', as: 'provider_login', via: [:get, :post]
  match '/auth/callback/:provider', to: 'admin/mail_job_schedules#callback', as: 'provider_callback', via: [:get, :post]
end

app/models/mail_job_schedule.rb
class MailJobSchedule < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_one :mail_ticket_token, dependent: :destroy
  belongs_to :mail_ticket_provider
  belongs_to :project
  belongs_to :tracker
  belongs_to :assigned_to, class_name: 'User'
  belongs_to :priority
  accepts_nested_attributes_for :mail_ticket_token
  delegate :access_token, :expires_at, :refresh_token, to: :mail_ticket_token
  validates :project_id, :priority_id, :assigned_to_id, :tracker_id, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: 'is invalid' }, uniqueness: { case_sensitive: false }  
  enum sync_status: { not_synced: 0, syncing: 1, synced: 2, failed: 3 }
  default_scope -> { where(active: true) }
  after_commit :generate_schedule_file, unless: :new_or_specific_column_changed?


  def provider_name
    mail_ticket_token&.mail_ticket_provider&.name&.capitalize
  end

  def is_account_verified?
    mail_ticket_token&.access_token.present?
  end

  private

  def new_or_specific_column_changed?
    (saved_change_to_sync_status? || saved_change_to_last_sync_email_count? || saved_change_to_sync_status? || saved_change_to_last_sync_email_count? || saved_change_to_message?)
  end

  def generate_schedule_file
    SchedulerFileGenerator.update_schedule if mail_ticket_token.access_token
  end
end

app/models/mail_ticket_provider.rb
class MailTicketProvider < ApplicationRecord
  encrypts :client_id, :client_secret, :tenant_id
  has_many :mail_ticket_tokens, dependent: :destroy

  default_scope -> { where(active: true) }
  delegate :provider_name, to: :mail_ticket_tokens
  validates :name, presence: true, uniqueness: true
  validates :client_id, :client_secret, :callback_url, presence: true
  validates :tenant_id, presence: true, if: -> { name == 'outlook' }
end

app/models/mail_ticket_token.rb
class MailTicketToken < ApplicationRecord
  encrypts :access_token, :refresh_token
  belongs_to :mail_ticket_provider
  belongs_to :mail_job_schedule

  enum status: { created: 0, authenticated: 1, failed: 2 }

  # default_scope -> { where(active: true) }
end

app/controllers/admin/mail_job_schedules_controller.rb
class Admin::MailJobSchedulesController < ApplicationController
  before_action :find_mail_job_schedule, only: %i[edit update show destroy start_mail_sync]
  before_action :require_admin
  layout 'admin'

  def index
    @jobs = MailJobSchedule.all
  end

  def new
    @mail_job_schedule = MailJobSchedule.new
    @mail_job_schedule.build_mail_ticket_token 
    @projects = Project.all
    @trackers = Tracker.all
    @users = User.all
    @priorities = IssuePriority.all
    @providers = MailTicketProvider.all
  end

  def create
    @mail_job_schedule = MailJobSchedule.new(mail_job_schedule_params)

    if @mail_job_schedule.save
      redirect_to admin_mail_job_schedules_path, notice: 'Mail Job Schedule created successfully.'
    else
      @projects = Project.all
      @trackers = Tracker.all
      @users = User.all
      @priorities = IssuePriority.all
      @providers = MailTicketProvider.all
      render :new
    end
  end

  def edit
    @mail_job_schedule.build_mail_ticket_token if @mail_job_schedule.mail_ticket_token.nil?
    @projects = Project.all
    @trackers = Tracker.all
    @users = User.all
    @priorities = IssuePriority.all
    @providers = MailTicketProvider.all
  end

  def update
    if @mail_job_schedule.update(mail_job_schedule_params)
      redirect_to admin_mail_job_schedules_path, notice: 'Mail Job Schedule updated successfully.'
    else
      @projects = Project.all
      @trackers = Tracker.all
      @users = User.all
      @priorities = IssuePriority.all
      @providers = MailTicketProvider.all
      render :edit
    end
  end

  def show
  end

  def destroy
    if @mail_job_schedule.destroy
      redirect_to admin_mail_job_schedules_path, notice: 'Mail Job Schedule deleted successfully.'
    end
  end

  def login
    url = OauthService.get_authorize_url_for_provider(params[:provider])
    redirect_to url
  end

  def callback
    token_data = OauthService.get_access_token_for_provider(params[:provider], params[:code])
    if token_data
      update_provider_configuration(token_data)
      flash[:notice] = "Logged in successfully! Email: #{token_data[:email]}"
    else
      flash[:error] = l(:error_oauth_failed)
    end
    redirect_to admin_mail_job_schedules_path
	end

  def start_mail_sync
    if @mail_job_schedule.is_account_verified?
      @mail_job_schedule.update(sync_status: 1)
      args = {tracker: @mail_job_schedule.tracker_id, priority: @mail_job_schedule.priority_id, assigned_to: @mail_job_schedule.assigned_to_id}
      service = EmailService.new(@mail_job_schedule, args)
      service.fetch_and_create_issues
    end
    redirect_to request.referer || admin_mail_job_schedules_path, notice: 'Mail sync successfully!'
  end

  private

  def find_mail_job_schedule
    @mail_job_schedule = MailJobSchedule.find(params[:id])
  end

  def mail_job_schedule_params
    params.require(:mail_job_schedule).permit(:project_id, :assigned_to_id, :email, 
      :tracker_id, :priority_id, :frequency, mail_ticket_token_attributes: [:id, :mail_ticket_provider_id] )
  end

  def update_provider_configuration(token_data)
    job = MailJobSchedule.find_by(email: token_data[:email])
    if job
      job.update(
        sync_status: 0,
        last_sync_email_count: 0,
        inbox_last_sync_at: nil
      )
      mail_ticket_token = job.mail_ticket_token
      mail_ticket_token.update(
        access_token: token_data[:access_token],
        refresh_access_token: token_data[:refresh_token],
        expires_at: token_data[:expires_at],
        status: 1,
      )
    end
  end
end

app/controllers/admin/mail_ticket_providers_controller.rb
class Admin::MailTicketProvidersController < ApplicationController
  before_action :find_mail_provider, only: %i[edit show update destroy]
  before_action :require_admin
  layout 'admin'


  def index
    @mail_providers = MailTicketProvider.all
  end

  def new
    @mail_provider = MailTicketProvider.new
  end

  def create
    @mail_provider = MailTicketProvider.new(mail_provider_params)

    if @mail_provider.save
      redirect_to admin_mail_ticket_providers_path, notice: 'Mail provider created successfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @mail_provider.update(mail_provider_params)
      redirect_to admin_mail_ticket_providers_path, notice: 'Mail provider updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    if @mail_provider.destroy
      redirect_to admin_mail_ticket_providers_path, notice: 'Mail provider deleted successfully.'
    else
      redirect_to admin_mail_ticket_providers_path, notice: 'Mail provider deleted failed.'
    end
  end

  private

  def find_mail_provider
    @mail_provider = MailTicketProvider.find(params[:id])
  end

  def mail_provider_params
    defaults = { active: true }

    params.require(:mail_ticket_provider).permit(:client_id, :client_secret, :tenant_id, :callback_url, :name).reverse_merge(defaults)
  end
end

app/helpers/mail_job_schedules_helper.rb
module MailJobSchedulesHelper
end

app/helpers/mail_ticket_providers_helper.rb
module MailTicketProvidersHelper
end

app/views/admin/mail_job_schedules/_form.html.erb
<%= form_with model: [:admin, mail_job_schedule], html: { class: 'new_issue'} do |f| %>
  <div class="box tabular filedroplistner">
    <div id="attributes" class="attributes">
      <div class="splitcontent">
        <% if mail_job_schedule.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(mail_job_schedule.errors.count, "error") %> prohibited this Microsoft mail from being saved:</h2>
            <ul>
              <% mail_job_schedule.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="splitcontentleft">
          <%= f.fields_for :mail_ticket_token do |token_form| %>
            <p>
              <%= token_form.label :mail_ticket_provider_id, "Provider" %>
              <%= token_form.select :mail_ticket_provider_id, options_from_collection_for_select(@providers, :id, :name, token_form.object.mail_ticket_provider&.id), prompt: 'Choose a provider', required: true %>
            </p>
          <% end %>
          <p>
            <%= f.label :project_id %>
            <%= f.select :project_id, options_from_collection_for_select(@projects, :id, :name, f.object.project_id), prompt: 'Choose a project', required: true %>
          </p>

          <p>
            <%= f.label :assigned_to_id %>
            <%= f.select :assigned_to_id, options_from_collection_for_select(@users, :id, :name, f.object.assigned_to_id), prompt: 'Choose a assignee', required: true %>
          </p>

          <p>
            <%= f.label :frequency %>
            <%= f.select :frequency, [["1 minute", "1.minute"], ["2 minutes", "2.minutes"], ["3 minutes", "3.minutes"], ["5 minutes", "5.minutes"], ["30 minutes", "30.minutes"]], {}, class: 'select' %>
          </p>
        </div>
        <div class="splitcontentright">
          <p>
            <%= f.label :email %>
            <%= f.email_field :email, required: true, size: 40 %>
          </p>
          <p>
            <%= f.label :tracker_id %>
            <%= f.select :tracker_id, options_from_collection_for_select(@trackers, :id, :name, f.object.tracker_id), prompt: 'Choose a tracker', required: true %>
          </p>

          <p>
            <%= f.label :priority_id %>
            <%= f.select :priority_id, options_from_collection_for_select(@priorities, :id, :name, f.object.priority_id), prompt: 'Choose a priority', required: true %>
          </p>
        </div>

         
      </div>
    </div>
  </div>
  <%= f.submit mail_job_schedule.new_record? ? 'Create' : 'Update', class: 'btn btn-primary' %>
<% end %>
<%= link_to "back", admin_mail_job_schedules_path %>

app/views/admin/mail_job_schedules/edit.html.erb
<h2>Edit Mail Job Scheduler</h2>
<%= render 'form', mail_job_schedule: @mail_job_schedule %>

app/views/admin/mail_job_schedules/index.html.erb
<div id="content">
  <div class="contextual">
    <%= link_to 'New', new_admin_mail_job_schedule_path, class: 'icon icon-add' %>
  </div>

  <% if @jobs.any? %>
    <div id="configure-data">
      <h3>Mail Job Schedulers</h3>
      <table class="list">
        <thead>
          <tr>
            <th>#</th>
            <th>Provider</th>
            <th>Mail</th>
            <th>Project</th>
            <th>Status</th>
            <th>Frequency</th>
            <th>Last Sync at</th>
            <th>Last Sync Count</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @jobs.each do | job | %>
            <tr>
              <td><%= link_to job.id, admin_mail_job_schedule_path(job) %></td>
              <td><%= job.provider_name %></td>
              <td><%= job.email %></td>
              <td><%= job.project.name %></td>
              <td><%= job.sync_status.humanize %></td>
              <td><%= job.frequency.gsub!('.', ' ') %> once</td>
              <td><%= job.inbox_last_sync_at ? time_ago_in_words(job.inbox_last_sync_at) : '-' %> </td>
              <td><%= job.last_sync_email_count || 0 %> </td>
              <td>
                <div style="display: flex;">
                  <%= link_to 'Edit', edit_admin_mail_job_schedule_path(job), class: "icon icon-edit" %> |
                  <%= link_to 'Delete', admin_mail_job_schedule_path(job), method: :delete, class: "icon icon-del" %> |
                  <%= link_to job.is_account_verified? ? "Re-Authenticate" : "Authenticate", provider_login_path(job.provider_name.downcase), method: :post, class: "icon icon-ok" if job.provider_name%>
                  <% if job.is_account_verified? %>
                    |
                    <%= link_to "Sync", start_mail_sync_path(job), class: "icon icon-roles", title: 'Manual Sync' %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>No job configuration found.</p>
  <% end %>
</div>

app/views/admin/mail_job_schedules/new.html.erb
  <h2>Mail Job Scheduler</h2>

<%= render 'form', mail_job_schedule: @mail_job_schedule %>

app/views/admin/mail_job_schedules/show.html.erb
<div id="content">
  <div class="contextual">
    <%= link_to 'New', new_admin_mail_job_schedule_path, class: 'icon icon-add' %> |
    <%= link_to 'Edit', edit_admin_mail_job_schedule_path(@mail_job_schedule), class: 'icon icon-edit' %> |
    <% if @mail_job_schedule.is_account_verified? %>
      <%= link_to "Sync", start_mail_sync_path(@mail_job_schedule), class: "icon icon-roles", title: 'Manual Sync' %> |
    <% end %>
    <%= link_to "<< back", admin_mail_job_schedules_path %>
  </div>

    <div id="configure-data">
      <table class="list">
        <tr>
          <td>Provider</td>
          <td><%= @mail_job_schedule.provider_name %></td>
        </tr>
        <tr>
          <td>Mail</td>
          <td><%= @mail_job_schedule.email %></td>
        </tr>
        <tr>
          <td>Project</td>
          <td><%= @mail_job_schedule.project.name %></td>
        </tr>
        <tr>
          <td>Status</td>
          <td><%= @mail_job_schedule.sync_status.humanize %></td>
        </tr>
        <tr>
          <td>Frequency</td>
          <td><%= @mail_job_schedule.frequency.gsub!('.', ' ') %> once</td>
        </tr>
        <tr>
          <td>Inbox Last Sync at</td>
          <td><%= @mail_job_schedule.inbox_last_sync_at ? time_ago_in_words(@mail_job_schedule.inbox_last_sync_at) : '-' %> </td>
        </tr>
        <tr>
          <td> Last Sync Mail Count </td>
          <td><%= @mail_job_schedule.last_sync_email_count || 0 %> </td>
        </tr>
        <tr>
          <td> Error </td>
          <td><%= @mail_job_schedule.message || 'n/a' %> </td>
        </tr>
      </table>
    </div>
</div>

app/views/admin/mail_ticket_providers/_form.html.erb
<%= form_with model: [:admin, mail_provider], html: { class: 'new_issue'} do |f| %>
  <div class="box tabular filedroplistner">
    <div id="attributes" class="attributes">
      <% if mail_provider.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(mail_provider.errors.count, "error") %> prohibited this from being saved:</h2>
            <ul>
              <% mail_provider.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <div class="splitcontent">
        <div class="splitcontentleft">
          <p>
            <%= f.label :name %>
            <%= f.select :name, options_for_select([['Outlook', 'outlook'], ['Gmail', 'gmail']], f.object.name), { prompt: 'Choose an email provider'} , { id:'provider' }%>
          </p>
          <p>
            <%= f.label :client_id %>
            <%= f.text_field :client_id, size: 100 %>
          </p>

          <p>
            <%= f.label :client_secret %>
            <%= f.text_field :client_secret, size: 100 %>
          </p>

          <p id='tenant_id_wrapper'>
            <%= f.label :tenant_id %>
            <%= f.text_field :tenant_id, size: 100 %>
          </p>

          <p>
            <%= f.label :callback_url %>
            <%= f.url_field :callback_url, size: 100 %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <%= f.submit mail_provider.new_record? ? 'Create' : 'Update', class: 'btn btn-primary' %>
<% end %>
<%= link_to "back", admin_mail_ticket_providers_path %>

<script>
  var tenantIdWrapper = "tenant_id_wrapper";
  var providerId = "provider";

  function hideTenantField() {
    var selectValue = $("#"+providerId).val();
    if(selectValue === 'gmail') {
      $("#"+tenantIdWrapper).addClass('hidden')
    } else {
      $("#"+tenantIdWrapper).removeClass('hidden')
    }
  }

  $("#provider").on('change', () => {
    hideTenantField()
  })

  $(document).ready(function(){
    hideTenantField()
  })
</script>

app/views/admin/mail_ticket_providers/edit.html.erb
<h2>Edit Mail Provider</h2>
<%= render 'form', mail_provider: @mail_provider %>

app/views/admin/mail_ticket_providers/index.html.erb
<div>
  <div class="contextual">
    <%= link_to 'New', new_admin_mail_ticket_provider_path, class: 'icon icon-add' %>
  </div>

  <% if @mail_providers.any? %>
    <div id="configure-data">
      <h3>Mail Providers</h3>
      <table class="list">
        <thead>
          <tr>
            <th>Provider</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @mail_providers.each do | mail_provider | %>
            <tr>
              <td><%= mail_provider.name.capitalize %></td>
              <td><%= mail_provider.active  ? 'Active' : 'Inactive' %></td>
              <td>
                <%= link_to 'Edit', edit_admin_mail_ticket_provider_path(mail_provider), class: "icon icon-edit" %> |
                <%= link_to 'Delete', admin_mail_ticket_provider_path(mail_provider), method: :delete, class: "icon icon-del"  %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>No mail provider found.</p>
  <% end %>
</div>

app/views/admin/mail_ticket_providers/new.html.erb
  <h2>Mail Provider</h2>

<%= render 'form', mail_provider: @mail_provider %>